-- Inserir palavras-chave iniciais da Matutta Máquinas e Ferramentas
INSERT INTO keywords (termo) VALUES

-- Informática
('notebook'),
('computador desktop'),
('monitor'),
('impressora'),
('scanner'),
('projetor'),
('projetor multimídia'),
('tela de projeção'),
('tablet'),
('nobreak'),
('estabilizador'),
('roteador'),
('switch'),
('webcam'),
('teclado'),
('mouse'),
('headset'),
('pen drive'),
('hd externo'),
('servidor'),
('impressora multifuncional'),
('lousa digital'),
('lousa interativa'),

-- Eletrônicos e Comunicação
('smartphone'),
('rádio comunicador'),
('câmera de segurança'),
('dvr'),
('alarme'),
('interfone'),
('rastreador veicular'),
('central telefônica'),
('aparelho de telefone'),
('câmera fotográfica'),
('filmadora'),
('drone'),
('televisão'),
('smart tv'),
('totem de autoatendimento'),
('sistema de controle de acesso'),
('controle de acesso biométrico'),
('detector de metais'),
('relógio de ponto'),
('catraca'),
('cofre'),

-- Mobiliário
('cadeira'),
('mesa'),
('armário'),
('arquivo'),
('estante'),
('sofá'),
('divisória'),
('lousa'),
('quadro branco'),
('carteira escolar'),
('mesa de professor'),
('armário escolar'),
('estante para livros'),
('persiana'),
('cortina'),
('blackout'),
('tapete'),
('capacho'),

-- Eletrodomésticos
('ar condicionado'),
('ventilador'),
('climatizador'),
('bebedouro'),
('purificador de água'),
('filtro de água'),
('cafeteira'),
('micro-ondas'),
('geladeira'),
('frigobar'),
('fogão'),
('freezer'),
('bebedouro escolar'),
('frigobar hospitalar'),
('dispensador de álcool automático'),
('dispenser de sabão'),

-- Ferramentas e Máquinas
('furadeira'),
('parafusadeira'),
('esmerilhadeira'),
('lixadeira'),
('compressor'),
('gerador'),
('martelo'),
('chave combinada'),
('alicate'),
('nível'),
('trena'),
('martelete'),
('lavadora de alta pressão'),
('motosserra'),
('roçadeira'),
('betoneira'),
('andaime'),
('escada'),
('guincho'),
('talha elétrica'),
('furadeira de impacto'),
('parafusadeira de impacto'),
('serra circular'),
('serra tico-tico'),

-- EPI e Segurança
('capacete'),
('luva'),
('bota de segurança'),
('óculos de proteção'),
('protetor auricular'),
('cinto de segurança'),
('colete refletivo'),
('uniforme'),
('trava queda'),
('extintor de incêndio'),
('mangueira de incêndio'),

-- Limpeza
('aspirador de pó'),
('enceradeira'),
('lavadora de piso'),
('mop'),
('vassoura'),
('lixeira'),
('saco de lixo'),
('detergente'),
('desinfetante'),
('álcool'),
('papel higiênico'),
('papel toalha'),

-- Elétrica e Iluminação
('lâmpada led'),
('refletor'),
('luminária'),
('fio elétrico'),
('disjuntor'),
('tomada'),
('interruptor'),
('quadro elétrico'),
('extensão elétrica'),
('painel solar'),
('inversor solar'),
('bateria solar'),
('carregador veicular elétrico'),

-- Hidráulica
('bomba d água'),
('motobomba'),
('mangueira'),
('caixa d água'),
('conexão pvc'),
('tubo pvc'),
('registro'),
('válvula'),

-- Saúde básica
('cadeira de rodas'),
('muleta'),
('termômetro'),
('oxímetro'),
('kit primeiros socorros'),
('esfigmomanômetro'),
('maca'),
('balança'),
('colchão'),
('travesseiro'),
('lençol'),
('cadeira de banho'),

-- Esporte e Lazer
('bola'),
('rede esportiva'),
('colchonete'),
('haltere'),
('uniforme esportivo'),
('bicicleta'),
('kit material esportivo'),

-- Escritório e Papelaria
('calculadora'),
('grampeador'),
('perfurador'),
('arquivo morto'),
('pasta'),
('caixa organizadora'),
('bandeira'),
('material de escritório'),

-- Câmeras e Monitoramento
('câmera ip'),
('câmera de monitoramento'),
('sistema de monitoramento')

ON CONFLICT (termo) DO NOTHING;
